---
# Velero for Kubernetes backup and disaster recovery
apiVersion: v1
kind: Namespace
metadata:
  name: velero
---
# Install Velero using the official Helm chart
# This configuration assumes you have S3-compatible storage (like MinIO) for backups
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: velero
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 5.2.2
    chart: velero
    helm:
      values: |
        configuration:
          backupStorageLocation:
          - name: default
            provider: aws
            bucket: kubernetes-backups
            config:
              region: us-east-1
              s3ForcePathStyle: "true"
              s3Url: http://minio.backup.svc.cluster.local:9000
          volumeSnapshotLocation:
          - name: default
            provider: csi
            config:
              cluster: kubernetes-cluster
          
        credentials:
          useSecret: true
          existingSecret: velero-credentials
          
        initContainers:
        - name: velero-plugin-for-csi
          image: velero/velero-plugin-for-csi:v0.7.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /target
            name: plugins
        - name: velero-plugin-for-aws
          image: velero/velero-plugin-for-aws:v1.8.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /target
            name: plugins
            
        schedules:
          daily-backup:
            disabled: false
            schedule: "0 2 * * *"  # Daily at 2 AM
            template:
              ttl: "720h"  # 30 days
              includedNamespaces:
              - "*"
              excludedNamespaces:
              - kube-system
              - kube-public
              - kube-node-lease
              storageLocation: default
              volumeSnapshotLocations:
              - default
              
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# MinIO for S3-compatible backup storage
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2023-12-07T04-16-00Z
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        env:
        - name: MINIO_ROOT_USER
          value: "admin"
        - name: MINIO_ROOT_PASSWORD
          value: "kubernetes-backup-admin"
        ports:
        - containerPort: 9000
        - containerPort: 9001
        volumeMounts:
        - name: minio-storage
          mountPath: /data
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
      volumes:
      - name: minio-storage
        persistentVolumeClaim:
          claimName: minio-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: backup
spec:
  storageClassName: proxmox-rbd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi