---
- name: Update system packages
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600

- name: Install required system packages
  apt:
    name:
      - curl
      - wget
      - gnupg2
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - htop
      - vim
      - net-tools
    state: present

- name: Disable swap permanently
  lineinfile:
    path: /etc/fstab
    regexp: '.*swap.*'
    state: absent
  notify: disable swap

- name: Disable swap immediately
  command: swapoff -a
  changed_when: false

- name: Load required kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Add kernel modules to load at boot
  lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: "{{ item }}"
    create: yes
  loop:
    - overlay
    - br_netfilter

- name: Configure sysctl parameters for Kubernetes
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/k8s.conf
  loop:
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { name: 'net.ipv4.ip_forward', value: '1' }

- name: Enable and start containerd
  systemd:
    name: containerd
    state: started
    enabled: yes

- name: Enable and start kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes

- name: Configure containerd for systemd cgroup
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '            SystemdCgroup = false'
    line: '            SystemdCgroup = true'
    backup: yes
  notify: restart containerd

- name: Create kubernetes config directory
  file:
    path: /etc/kubernetes
    state: directory
    mode: '0755'