---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
# Prometheus Stack using kube-prometheus-stack Helm chart
# This provides Prometheus, Grafana, AlertManager, and essential exporters
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 56.21.4
    chart: kube-prometheus-stack
    helm:
      values: |
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: proxmox-rbd
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 50Gi
            retention: 30d
            retentionSize: 45GB
            
        grafana:
          persistence:
            enabled: true
            storageClassName: proxmox-rbd
            size: 10Gi
          adminPassword: kubernetes-admin
          service:
            type: LoadBalancer
            
        alertmanager:
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: proxmox-rbd
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
                      
        # Enable monitoring of Proxmox nodes
        kubeEtcd:
          enabled: true
        kubeControllerManager:
          enabled: true
        kubeScheduler:
          enabled: true
        kubeProxy:
          enabled: true
        kubelet:
          enabled: true
          
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true