# High Availability Kubernetes Cluster Configuration
deployment_profile: ha-cluster
kubernetes_version: "1.33.4"
template_id: 9005

proxmox:
  host: "10.10.1.21"
  token: "packer@pam!packer=7b2a3da7-bd30-4772-a6b0-874aa9b2f3a5"
  node: "hp4"
  storage: "rbd"

cluster:
  pod_subnet: "10.244.0.0/16"
  service_subnet: "10.96.0.0/12"
  control_plane_endpoint: "10.10.1.99:6443"
  
node_specs:
  control_plane:
    count: 3
    cores: 4
    memory: 8192
    disk_size: 50
  worker:
    count: 4
    cores: 4
    memory: 16384
    disk_size: 100
    
networking:
  cni: "cilium"
  cni_version: "1.15.0"
  load_balancer: "metallb"
  ingress: "nginx"

platform_services:
  monitoring: true
  logging: true
  backup: true
  certificates: true