# Single Node Kubernetes Cluster Configuration
deployment_profile: single-node
kubernetes_version: "1.33.4"
template_id: 9005

proxmox:
  host: "10.10.1.21"
  token: "packer@pam!packer=7b2a3da7-bd30-4772-a6b0-874aa9b2f3a5"
  node: "hp4"
  storage: "rbd"

cluster:
  pod_subnet: "10.244.0.0/16"
  service_subnet: "10.96.0.0/12"
  
# Single node gets full resources
node_specs:
  control_plane:
    cores: 8
    memory: 16384
    disk_size: 100
    
networking:
  cni: "cilium"
  cni_version: "1.15.0"