---
# Proxmox CSI Plugin for dynamic persistent volume provisioning
# Provides Ceph RBD storage integration
apiVersion: v1
kind: Namespace
metadata:
  name: csi-proxmox
---
# Proxmox CSI Secret for authentication
apiVersion: v1
kind: Secret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
type: Opaque
stringData:
  config.yaml: |-
    clusters:
    - url: https://10.10.1.21:8006/api2/json
      insecure: false
      token_id: "kubernetes@pve"
      token_secret: "your-token-secret-here"
      region: cluster
---
# Storage Class for Proxmox Ceph RBD
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-rbd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.proxmox.sinextra.dev
parameters:
  storage: ceph-rbd
  csi.storage.k8s.io/fstype: ext4
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
# Fast SSD Storage Class (if available)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-rbd-fast
provisioner: csi.proxmox.sinextra.dev
parameters:
  storage: ceph-rbd-fast
  csi.storage.k8s.io/fstype: ext4
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
# CSI Driver deployment via Helm
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxmox-csi-plugin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://sergelogvinov.github.io/charts
    targetRevision: 0.2.8
    chart: proxmox-csi-plugin
    helm:
      values: |
        # Proxmox cluster configuration
        config:
          clusters:
          - url: https://10.10.1.21:8006/api2/json
            insecure: false
            token_id: "kubernetes@pve"
            token_secret: "your-token-secret-here"
            region: cluster
        
        # CSI Controller configuration  
        controller:
          replicaCount: 2
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 200m
              memory: 256Mi
        
        # CSI Node configuration
        node:
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 200m
              memory: 256Mi
              
        # Storage classes
        storageClass:
        - name: proxmox-rbd
          storage: ceph-rbd
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          isDefault: true
        - name: proxmox-rbd-fast  
          storage: ceph-rbd-fast
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          isDefault: false

  destination:
    server: https://kubernetes.default.svc
    namespace: csi-proxmox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true