---
- name: Deploy Production-Grade Kubernetes Cluster on Proxmox
  hosts: kubernetes
  become: yes
  gather_facts: yes
  vars:
    kubernetes_version: "1.29"
    pod_network_cidr: "10.244.0.0/16"
    service_subnet: "10.96.0.0/12"
    control_plane_vip: "{{ hostvars['localhost']['control_plane_vip'] | default('10.10.1.100') }}"
    keepalived_interface: "ens18"
    metallb_pool_start: "10.10.1.200"
    metallb_pool_end: "10.10.1.220"

  roles:
    - common
    - { role: keepalived, when: "'control_plane' in group_names" }
    - kubernetes

- name: Initialize Kubernetes Cluster
  hosts: control_plane[0]
  become: yes
  vars:
    control_plane_vip: "{{ hostvars['localhost']['control_plane_vip'] | default('10.10.1.100') }}"
    pod_network_cidr: "10.244.0.0/16"
    service_subnet: "10.96.0.0/12"
    
  roles:
    - kubernetes_init

- name: Join Control Plane Nodes
  hosts: control_plane[1:]
  become: yes
  vars:
    control_plane_vip: "{{ hostvars['localhost']['control_plane_vip'] | default('10.10.1.100') }}"
    
  roles:
    - kubernetes_join_control_plane

- name: Join Worker Nodes
  hosts: workers
  become: yes
  vars:
    control_plane_vip: "{{ hostvars['localhost']['control_plane_vip'] | default('10.10.1.100') }}"
    
  roles:
    - kubernetes_join_workers

- name: Post-Installation Configuration
  hosts: control_plane[0]
  become: yes
  vars:
    metallb_pool_start: "10.10.1.200"
    metallb_pool_end: "10.10.1.220"
    
  roles:
    - kubernetes_post_install